<?xml version="1.0" encoding="utf-8"?><Database Name="MPAY" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=MPAY;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MPAYConnectionString" Provider="System.Data.SqlClient" />
</Database>