#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaricoPay.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FIN")]
	public partial class DBStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBStoreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MPAYConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsExistsUser")]
		public ISingleResult<IsExistsUserResult> IsExistsUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<IsExistsUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Lay_PhanQuyen_ID")]
		public ISingleResult<SP_Lay_PhanQuyen_IDResult> SP_Lay_PhanQuyen_ID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idsite)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, idsite);
			return ((ISingleResult<SP_Lay_PhanQuyen_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateDocTotal")]
		public int sp_UpdateDocTotal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getClaimApproved")]
		public ISingleResult<sp_getClaimApprovedResult> sp_getClaimApproved([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<sp_getClaimApprovedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetClaimExpenses_Print")]
		public ISingleResult<sp_GetClaimExpenses_PrintResult> sp_GetClaimExpenses_Print([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GetClaimExpenses_PrintResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GenaCode")]
		public ISingleResult<sp_GenaCodeResult> sp_GenaCode([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GenaCodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LoadTotalClaim4Doc")]
		public ISingleResult<sp_LoadTotalClaim4DocResult> sp_LoadTotalClaim4Doc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_LoadTotalClaim4DocResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getClaimSaved")]
		public ISingleResult<sp_getClaimSavedResult> sp_getClaimSaved([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(150)")] string type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, type);
			return ((ISingleResult<sp_getClaimSavedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetClaimExpensesOffice_Print")]
		public ISingleResult<sp_GetClaimExpensesOffice_PrintResult> sp_GetClaimExpensesOffice_Print([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GetClaimExpensesOffice_PrintResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getTravelDetail")]
		public ISingleResult<sp_getTravelDetailResult> sp_getTravelDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_getTravelDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetTravelRequest_Print")]
		public ISingleResult<sp_GetTravelRequest_PrintResult> sp_GetTravelRequest_Print([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GetTravelRequest_PrintResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserInfo_TravelExists")]
		public ISingleResult<sp_GetUserInfo_TravelExistsResult> sp_GetUserInfo_TravelExists([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GetUserInfo_TravelExistsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserInfo")]
		public ISingleResult<sp_GetUserInfoResult> sp_GetUserInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<sp_GetUserInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserInfo_ClaimExists")]
		public ISingleResult<sp_GetUserInfo_ClaimExistsResult> sp_GetUserInfo_ClaimExists([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_GetUserInfo_ClaimExistsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getClaimDetail")]
		public ISingleResult<sp_getClaimDetailResult> sp_getClaimDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isSubtotal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code, isSubtotal);
			return ((ISingleResult<sp_getClaimDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getTravelDetailSales")]
		public ISingleResult<sp_getTravelDetailSalesResult> sp_getTravelDetailSales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
			return ((ISingleResult<sp_getTravelDetailSalesResult>)(result.ReturnValue));
		}
	}
	
	public partial class IsExistsUserResult
	{
		
		private string _Username;
		
		private string _Fullname;
		
		private System.Nullable<int> _Department_FK;
		
		private string _Market_FK;
		
		private System.Nullable<int> _Position_FK;
		
		private string _Email;
		
		private string _Recommender;
		
		private string _Pass;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _Function_FK;
		
		private System.Nullable<int> _IsManager;
		
		private string _EmployeeCode;
		
		private System.Nullable<int> _Area_FK;
		
		private System.Nullable<int> _Level_FK;
		
		public IsExistsUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(150)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_FK", DbType="Int")]
		public System.Nullable<int> Department_FK
		{
			get
			{
				return this._Department_FK;
			}
			set
			{
				if ((this._Department_FK != value))
				{
					this._Department_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market_FK", DbType="VarChar(50)")]
		public string Market_FK
		{
			get
			{
				return this._Market_FK;
			}
			set
			{
				if ((this._Market_FK != value))
				{
					this._Market_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_FK", DbType="Int")]
		public System.Nullable<int> Position_FK
		{
			get
			{
				return this._Position_FK;
			}
			set
			{
				if ((this._Position_FK != value))
				{
					this._Position_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recommender", DbType="VarChar(50)")]
		public string Recommender
		{
			get
			{
				return this._Recommender;
			}
			set
			{
				if ((this._Recommender != value))
				{
					this._Recommender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(500)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Function_FK", DbType="Int")]
		public System.Nullable<int> Function_FK
		{
			get
			{
				return this._Function_FK;
			}
			set
			{
				if ((this._Function_FK != value))
				{
					this._Function_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManager", DbType="Int")]
		public System.Nullable<int> IsManager
		{
			get
			{
				return this._IsManager;
			}
			set
			{
				if ((this._IsManager != value))
				{
					this._IsManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeCode", DbType="VarChar(50)")]
		public string EmployeeCode
		{
			get
			{
				return this._EmployeeCode;
			}
			set
			{
				if ((this._EmployeeCode != value))
				{
					this._EmployeeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_FK", DbType="Int")]
		public System.Nullable<int> Area_FK
		{
			get
			{
				return this._Area_FK;
			}
			set
			{
				if ((this._Area_FK != value))
				{
					this._Area_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level_FK", DbType="Int")]
		public System.Nullable<int> Level_FK
		{
			get
			{
				return this._Level_FK;
			}
			set
			{
				if ((this._Level_FK != value))
				{
					this._Level_FK = value;
				}
			}
		}
	}
	
	public partial class SP_Lay_PhanQuyen_IDResult
	{
		
		private string _IDSITE;
		
		private string _MaNV;
		
		private string _IDQuyen;
		
		public SP_Lay_PhanQuyen_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSITE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDSITE
		{
			get
			{
				return this._IDSITE;
			}
			set
			{
				if ((this._IDSITE != value))
				{
					this._IDSITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="VarChar(50)")]
		public string IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this._IDQuyen = value;
				}
			}
		}
	}
	
	public partial class sp_getClaimApprovedResult
	{
		
		private string _Values;
		
		private string _Text;
		
		public sp_getClaimApprovedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this._Values = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
	}
	
	public partial class sp_GetClaimExpenses_PrintResult
	{
		
		private string _Type;
		
		private string _TypeText;
		
		private string _Market;
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _FullNameRec;
		
		private System.Nullable<System.DateTime> _TDate;
		
		private System.Nullable<System.DateTime> _FDate;
		
		private string _Purpose;
		
		private System.Nullable<int> _NoDays;
		
		private System.Nullable<System.DateTime> _DateRec;
		
		private string _Signture;
		
		public sp_GetClaimExpenses_PrintResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeText", DbType="VarChar(36)")]
		public string TypeText
		{
			get
			{
				return this._TypeText;
			}
			set
			{
				if ((this._TypeText != value))
				{
					this._TypeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="NVarChar(250)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(250)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(250)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(150)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRec", DbType="NVarChar(150)")]
		public string FullNameRec
		{
			get
			{
				return this._FullNameRec;
			}
			set
			{
				if ((this._FullNameRec != value))
				{
					this._FullNameRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Int")]
		public System.Nullable<int> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRec", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateRec
		{
			get
			{
				return this._DateRec;
			}
			set
			{
				if ((this._DateRec != value))
				{
					this._DateRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signture", DbType="VarChar(250)")]
		public string Signture
		{
			get
			{
				return this._Signture;
			}
			set
			{
				if ((this._Signture != value))
				{
					this._Signture = value;
				}
			}
		}
	}
	
	public partial class sp_GenaCodeResult
	{
		
		private System.Nullable<int> _Column1;
		
		public sp_GenaCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_LoadTotalClaim4DocResult
	{
		
		private string _Description;
		
		private string _Total_VND;
		
		private string _NoDays;
		
		private string _AVG_VND;
		
		public sp_LoadTotalClaim4DocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_VND", DbType="VarChar(250)")]
		public string Total_VND
		{
			get
			{
				return this._Total_VND;
			}
			set
			{
				if ((this._Total_VND != value))
				{
					this._Total_VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="VarChar(10)")]
		public string NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVG_VND", DbType="VarChar(250)")]
		public string AVG_VND
		{
			get
			{
				return this._AVG_VND;
			}
			set
			{
				if ((this._AVG_VND != value))
				{
					this._AVG_VND = value;
				}
			}
		}
	}
	
	public partial class sp_getClaimSavedResult
	{
		
		private string _Values;
		
		private string _Text;
		
		public sp_getClaimSavedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this._Values = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
	}
	
	public partial class sp_GetClaimExpensesOffice_PrintResult
	{
		
		private string _Type;
		
		private string _TypeText;
		
		private string _Market;
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _FullNameRec;
		
		private System.Nullable<System.DateTime> _TDate;
		
		private System.Nullable<System.DateTime> _FDate;
		
		private string _Purpose;
		
		private System.Nullable<int> _NoDays;
		
		private System.Nullable<System.DateTime> _DateRec;
		
		private System.Nullable<decimal> _DaTamUng;
		
		private string _Costcenter;
		
		private string _Signture;
		
		public sp_GetClaimExpensesOffice_PrintResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeText", DbType="VarChar(50)")]
		public string TypeText
		{
			get
			{
				return this._TypeText;
			}
			set
			{
				if ((this._TypeText != value))
				{
					this._TypeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="NVarChar(250)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(250)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(250)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(150)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRec", DbType="NVarChar(150)")]
		public string FullNameRec
		{
			get
			{
				return this._FullNameRec;
			}
			set
			{
				if ((this._FullNameRec != value))
				{
					this._FullNameRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Int")]
		public System.Nullable<int> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRec", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateRec
		{
			get
			{
				return this._DateRec;
			}
			set
			{
				if ((this._DateRec != value))
				{
					this._DateRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaTamUng", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DaTamUng
		{
			get
			{
				return this._DaTamUng;
			}
			set
			{
				if ((this._DaTamUng != value))
				{
					this._DaTamUng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costcenter", DbType="VarChar(50)")]
		public string Costcenter
		{
			get
			{
				return this._Costcenter;
			}
			set
			{
				if ((this._Costcenter != value))
				{
					this._Costcenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signture", DbType="VarChar(250)")]
		public string Signture
		{
			get
			{
				return this._Signture;
			}
			set
			{
				if ((this._Signture != value))
				{
					this._Signture = value;
				}
			}
		}
	}
	
	public partial class sp_getTravelDetailResult
	{
		
		private string _Code_FK;
		
		private string _Charges_FK;
		
		private string _Description;
		
		private System.Nullable<decimal> _SoTien;
		
		private System.Nullable<int> _SoLuong;
		
		private string _DonViTinh;
		
		private System.Nullable<decimal> _Cong;
		
		private System.Nullable<bool> _IsTamUng;
		
		private System.Nullable<decimal> _ID;
		
		public sp_getTravelDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_FK", DbType="VarChar(50)")]
		public string Code_FK
		{
			get
			{
				return this._Code_FK;
			}
			set
			{
				if ((this._Code_FK != value))
				{
					this._Code_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charges_FK", DbType="VarChar(50)")]
		public string Charges_FK
		{
			get
			{
				return this._Charges_FK;
			}
			set
			{
				if ((this._Charges_FK != value))
				{
					this._Charges_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this._SoTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this._DonViTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Cong
		{
			get
			{
				return this._Cong;
			}
			set
			{
				if ((this._Cong != value))
				{
					this._Cong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTamUng", DbType="Bit")]
		public System.Nullable<bool> IsTamUng
		{
			get
			{
				return this._IsTamUng;
			}
			set
			{
				if ((this._IsTamUng != value))
				{
					this._IsTamUng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	public partial class sp_GetTravelRequest_PrintResult
	{
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _Approver;
		
		private string _TelContact;
		
		private System.Nullable<System.DateTime> _TDate;
		
		private System.Nullable<System.DateTime> _FDate;
		
		private string _Purpose;
		
		private System.Nullable<double> _NoDays;
		
		private System.Nullable<System.DateTime> _DateRec;
		
		private string _Costcenter;
		
		private string _Destination;
		
		private string _Itenerary;
		
		private System.Nullable<bool> _ByCar;
		
		private System.Nullable<bool> _ByTrain;
		
		private System.Nullable<bool> _ByPlane;
		
		private System.Nullable<bool> _CarAriPort;
		
		private System.Nullable<bool> _CarTravel;
		
		private System.Nullable<bool> _BookHotel;
		
		private System.Nullable<bool> _BookTicket;
		
		private System.Nullable<bool> _Other;
		
		private string _DetailOther;
		
		private System.Nullable<double> _Advance;
		
		private string _Signture;
		
		private string _DPNo;
		
		public sp_GetTravelRequest_PrintResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(250)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(250)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(150)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approver", DbType="NVarChar(150)")]
		public string Approver
		{
			get
			{
				return this._Approver;
			}
			set
			{
				if ((this._Approver != value))
				{
					this._Approver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelContact", DbType="VarChar(50)")]
		public string TelContact
		{
			get
			{
				return this._TelContact;
			}
			set
			{
				if ((this._TelContact != value))
				{
					this._TelContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Float")]
		public System.Nullable<double> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRec", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateRec
		{
			get
			{
				return this._DateRec;
			}
			set
			{
				if ((this._DateRec != value))
				{
					this._DateRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costcenter", DbType="VarChar(50)")]
		public string Costcenter
		{
			get
			{
				return this._Costcenter;
			}
			set
			{
				if ((this._Costcenter != value))
				{
					this._Costcenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(500)")]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this._Destination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Itenerary", DbType="NVarChar(500)")]
		public string Itenerary
		{
			get
			{
				return this._Itenerary;
			}
			set
			{
				if ((this._Itenerary != value))
				{
					this._Itenerary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByCar", DbType="Bit")]
		public System.Nullable<bool> ByCar
		{
			get
			{
				return this._ByCar;
			}
			set
			{
				if ((this._ByCar != value))
				{
					this._ByCar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByTrain", DbType="Bit")]
		public System.Nullable<bool> ByTrain
		{
			get
			{
				return this._ByTrain;
			}
			set
			{
				if ((this._ByTrain != value))
				{
					this._ByTrain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByPlane", DbType="Bit")]
		public System.Nullable<bool> ByPlane
		{
			get
			{
				return this._ByPlane;
			}
			set
			{
				if ((this._ByPlane != value))
				{
					this._ByPlane = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarAriPort", DbType="Bit")]
		public System.Nullable<bool> CarAriPort
		{
			get
			{
				return this._CarAriPort;
			}
			set
			{
				if ((this._CarAriPort != value))
				{
					this._CarAriPort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarTravel", DbType="Bit")]
		public System.Nullable<bool> CarTravel
		{
			get
			{
				return this._CarTravel;
			}
			set
			{
				if ((this._CarTravel != value))
				{
					this._CarTravel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookHotel", DbType="Bit")]
		public System.Nullable<bool> BookHotel
		{
			get
			{
				return this._BookHotel;
			}
			set
			{
				if ((this._BookHotel != value))
				{
					this._BookHotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookTicket", DbType="Bit")]
		public System.Nullable<bool> BookTicket
		{
			get
			{
				return this._BookTicket;
			}
			set
			{
				if ((this._BookTicket != value))
				{
					this._BookTicket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="Bit")]
		public System.Nullable<bool> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailOther", DbType="NVarChar(500)")]
		public string DetailOther
		{
			get
			{
				return this._DetailOther;
			}
			set
			{
				if ((this._DetailOther != value))
				{
					this._DetailOther = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advance", DbType="Float")]
		public System.Nullable<double> Advance
		{
			get
			{
				return this._Advance;
			}
			set
			{
				if ((this._Advance != value))
				{
					this._Advance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signture", DbType="VarChar(250)")]
		public string Signture
		{
			get
			{
				return this._Signture;
			}
			set
			{
				if ((this._Signture != value))
				{
					this._Signture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPNo", DbType="VarChar(50)")]
		public string DPNo
		{
			get
			{
				return this._DPNo;
			}
			set
			{
				if ((this._DPNo != value))
				{
					this._DPNo = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserInfo_TravelExistsResult
	{
		
		private string _Market;
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _Email;
		
		private string _FullNameRec;
		
		private string _EmailRec;
		
		private System.Nullable<System.DateTime> _TDate;
		
		private System.Nullable<System.DateTime> _FDate;
		
		private string _Purpose;
		
		private string _Costcenter;
		
		private System.Nullable<double> _NoDays;
		
		private System.Nullable<System.DateTime> _DateRec;
		
		private string _NoteApprover;
		
		private string _Itenerary;
		
		private string _TelContact;
		
		private System.Nullable<bool> _ByCar;
		
		private System.Nullable<bool> _ByTrain;
		
		private System.Nullable<bool> _ByPlane;
		
		private System.Nullable<bool> _CarAriPort;
		
		private System.Nullable<bool> _CarTravel;
		
		private System.Nullable<bool> _BookHotel;
		
		private System.Nullable<bool> _BookTicket;
		
		private string _Destination;
		
		private string _StatusText;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<bool> _Other;
		
		private string _DetailOther;
		
		private string _DPNo;
		
		private System.Nullable<decimal> _AdvanceAmount;
		
		public sp_GetUserInfo_TravelExistsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="VarChar(150)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(250)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(150)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRec", DbType="NVarChar(150)")]
		public string FullNameRec
		{
			get
			{
				return this._FullNameRec;
			}
			set
			{
				if ((this._FullNameRec != value))
				{
					this._FullNameRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailRec", DbType="VarChar(50)")]
		public string EmailRec
		{
			get
			{
				return this._EmailRec;
			}
			set
			{
				if ((this._EmailRec != value))
				{
					this._EmailRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costcenter", DbType="VarChar(50)")]
		public string Costcenter
		{
			get
			{
				return this._Costcenter;
			}
			set
			{
				if ((this._Costcenter != value))
				{
					this._Costcenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Float")]
		public System.Nullable<double> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRec", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateRec
		{
			get
			{
				return this._DateRec;
			}
			set
			{
				if ((this._DateRec != value))
				{
					this._DateRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteApprover", DbType="NVarChar(500)")]
		public string NoteApprover
		{
			get
			{
				return this._NoteApprover;
			}
			set
			{
				if ((this._NoteApprover != value))
				{
					this._NoteApprover = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Itenerary", DbType="NVarChar(500)")]
		public string Itenerary
		{
			get
			{
				return this._Itenerary;
			}
			set
			{
				if ((this._Itenerary != value))
				{
					this._Itenerary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelContact", DbType="VarChar(50)")]
		public string TelContact
		{
			get
			{
				return this._TelContact;
			}
			set
			{
				if ((this._TelContact != value))
				{
					this._TelContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByCar", DbType="Bit")]
		public System.Nullable<bool> ByCar
		{
			get
			{
				return this._ByCar;
			}
			set
			{
				if ((this._ByCar != value))
				{
					this._ByCar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByTrain", DbType="Bit")]
		public System.Nullable<bool> ByTrain
		{
			get
			{
				return this._ByTrain;
			}
			set
			{
				if ((this._ByTrain != value))
				{
					this._ByTrain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByPlane", DbType="Bit")]
		public System.Nullable<bool> ByPlane
		{
			get
			{
				return this._ByPlane;
			}
			set
			{
				if ((this._ByPlane != value))
				{
					this._ByPlane = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarAriPort", DbType="Bit")]
		public System.Nullable<bool> CarAriPort
		{
			get
			{
				return this._CarAriPort;
			}
			set
			{
				if ((this._CarAriPort != value))
				{
					this._CarAriPort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarTravel", DbType="Bit")]
		public System.Nullable<bool> CarTravel
		{
			get
			{
				return this._CarTravel;
			}
			set
			{
				if ((this._CarTravel != value))
				{
					this._CarTravel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookHotel", DbType="Bit")]
		public System.Nullable<bool> BookHotel
		{
			get
			{
				return this._BookHotel;
			}
			set
			{
				if ((this._BookHotel != value))
				{
					this._BookHotel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookTicket", DbType="Bit")]
		public System.Nullable<bool> BookTicket
		{
			get
			{
				return this._BookTicket;
			}
			set
			{
				if ((this._BookTicket != value))
				{
					this._BookTicket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(500)")]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this._Destination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusText", DbType="VarChar(9)")]
		public string StatusText
		{
			get
			{
				return this._StatusText;
			}
			set
			{
				if ((this._StatusText != value))
				{
					this._StatusText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="Bit")]
		public System.Nullable<bool> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailOther", DbType="NVarChar(500)")]
		public string DetailOther
		{
			get
			{
				return this._DetailOther;
			}
			set
			{
				if ((this._DetailOther != value))
				{
					this._DetailOther = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPNo", DbType="VarChar(50)")]
		public string DPNo
		{
			get
			{
				return this._DPNo;
			}
			set
			{
				if ((this._DPNo != value))
				{
					this._DPNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> AdvanceAmount
		{
			get
			{
				return this._AdvanceAmount;
			}
			set
			{
				if ((this._AdvanceAmount != value))
				{
					this._AdvanceAmount = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserInfoResult
	{
		
		private string _Market;
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _Email;
		
		private string _FullNameRec;
		
		private string _EmailRec;
		
		private string _StatusText;
		
		private int _Status;
		
		private string _TelPhone;
		
		private string _BudgetOwner;
		
		private string _Costcenter;
		
		public sp_GetUserInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="VarChar(50)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(301)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(150)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(250)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRec", DbType="NVarChar(250)")]
		public string FullNameRec
		{
			get
			{
				return this._FullNameRec;
			}
			set
			{
				if ((this._FullNameRec != value))
				{
					this._FullNameRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailRec", DbType="VarChar(250)")]
		public string EmailRec
		{
			get
			{
				return this._EmailRec;
			}
			set
			{
				if ((this._EmailRec != value))
				{
					this._EmailRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusText", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string StatusText
		{
			get
			{
				return this._StatusText;
			}
			set
			{
				if ((this._StatusText != value))
				{
					this._StatusText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelPhone", DbType="VarChar(50)")]
		public string TelPhone
		{
			get
			{
				return this._TelPhone;
			}
			set
			{
				if ((this._TelPhone != value))
				{
					this._TelPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetOwner", DbType="NVarChar(500)")]
		public string BudgetOwner
		{
			get
			{
				return this._BudgetOwner;
			}
			set
			{
				if ((this._BudgetOwner != value))
				{
					this._BudgetOwner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costcenter", DbType="VarChar(50)")]
		public string Costcenter
		{
			get
			{
				return this._Costcenter;
			}
			set
			{
				if ((this._Costcenter != value))
				{
					this._Costcenter = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserInfo_ClaimExistsResult
	{
		
		private string _Market;
		
		private string _Department;
		
		private string _Fullname;
		
		private string _Position;
		
		private string _Email;
		
		private string _FullNameRec;
		
		private string _EmailRec;
		
		private System.Nullable<System.DateTime> _TDate;
		
		private System.Nullable<System.DateTime> _FDate;
		
		private string _Purpose;
		
		private System.Nullable<decimal> _DaTamUng;
		
		private System.Nullable<int> _NoDays;
		
		private System.Nullable<System.DateTime> _DateRec;
		
		private string _NoteApprover;
		
		private string _StatusText;
		
		private System.Nullable<int> _Status;
		
		private string _Type;
		
		private string _AdvanceDocNo;
		
		private string _NguoiThuHuong;
		
		public sp_GetUserInfo_ClaimExistsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="VarChar(150)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(250)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(250)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(150)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRec", DbType="NVarChar(150)")]
		public string FullNameRec
		{
			get
			{
				return this._FullNameRec;
			}
			set
			{
				if ((this._FullNameRec != value))
				{
					this._FullNameRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailRec", DbType="VarChar(150)")]
		public string EmailRec
		{
			get
			{
				return this._EmailRec;
			}
			set
			{
				if ((this._EmailRec != value))
				{
					this._EmailRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaTamUng", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DaTamUng
		{
			get
			{
				return this._DaTamUng;
			}
			set
			{
				if ((this._DaTamUng != value))
				{
					this._DaTamUng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Int")]
		public System.Nullable<int> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRec", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateRec
		{
			get
			{
				return this._DateRec;
			}
			set
			{
				if ((this._DateRec != value))
				{
					this._DateRec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteApprover", DbType="NVarChar(500)")]
		public string NoteApprover
		{
			get
			{
				return this._NoteApprover;
			}
			set
			{
				if ((this._NoteApprover != value))
				{
					this._NoteApprover = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusText", DbType="VarChar(9)")]
		public string StatusText
		{
			get
			{
				return this._StatusText;
			}
			set
			{
				if ((this._StatusText != value))
				{
					this._StatusText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceDocNo", DbType="VarChar(50)")]
		public string AdvanceDocNo
		{
			get
			{
				return this._AdvanceDocNo;
			}
			set
			{
				if ((this._AdvanceDocNo != value))
				{
					this._AdvanceDocNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThuHuong", DbType="NVarChar(200)")]
		public string NguoiThuHuong
		{
			get
			{
				return this._NguoiThuHuong;
			}
			set
			{
				if ((this._NguoiThuHuong != value))
				{
					this._NguoiThuHuong = value;
				}
			}
		}
	}
	
	public partial class sp_getClaimDetailResult
	{
		
		private string _Code_FK;
		
		private System.DateTime _Date;
		
		private string _No;
		
		private string _Notation;
		
		private string _Charges_FK;
		
		private string _Description;
		
		private string _Currency;
		
		private System.Nullable<double> _Rate;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _TotalVN;
		
		private string _PictureURL;
		
		private System.Nullable<decimal> _ID;
		
		private string _CompanyName;
		
		private string _Province;
		
		private string _VATCode;
		
		private System.Nullable<double> _VATAmount;
		
		private System.DateTime _FDate;
		
		private System.DateTime _TDate;
		
		private System.Nullable<int> _NoDays;
		
		private string _Purpose;
		
		private string _DetailExpenses;
		
		private string _Participant;
		
		private string _GL;
		
		private string _IO;
		
		private string _CompanyCode;
		
		private string _FileAttach;
		
		private string _Costcenter;
		
		private string _CurrencyDescription;
		
		public sp_getClaimDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_FK", DbType="VarChar(50)")]
		public string Code_FK
		{
			get
			{
				return this._Code_FK;
			}
			set
			{
				if ((this._Code_FK != value))
				{
					this._Code_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="VarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notation", DbType="VarChar(50)")]
		public string Notation
		{
			get
			{
				return this._Notation;
			}
			set
			{
				if ((this._Notation != value))
				{
					this._Notation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charges_FK", DbType="VarChar(50)")]
		public string Charges_FK
		{
			get
			{
				return this._Charges_FK;
			}
			set
			{
				if ((this._Charges_FK != value))
				{
					this._Charges_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(350)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(50)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this._Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Float")]
		public System.Nullable<double> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalVN
		{
			get
			{
				return this._TotalVN;
			}
			set
			{
				if ((this._TotalVN != value))
				{
					this._TotalVN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureURL", DbType="VarChar(350)")]
		public string PictureURL
		{
			get
			{
				return this._PictureURL;
			}
			set
			{
				if ((this._PictureURL != value))
				{
					this._PictureURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(350)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(150)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATCode", DbType="NVarChar(50)")]
		public string VATCode
		{
			get
			{
				return this._VATCode;
			}
			set
			{
				if ((this._VATCode != value))
				{
					this._VATCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATAmount", DbType="Float")]
		public System.Nullable<double> VATAmount
		{
			get
			{
				return this._VATAmount;
			}
			set
			{
				if ((this._VATAmount != value))
				{
					this._VATAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime NOT NULL")]
		public System.DateTime FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime NOT NULL")]
		public System.DateTime TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDays", DbType="Int")]
		public System.Nullable<int> NoDays
		{
			get
			{
				return this._NoDays;
			}
			set
			{
				if ((this._NoDays != value))
				{
					this._NoDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="NVarChar(350)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this._Purpose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailExpenses", DbType="NVarChar(350)")]
		public string DetailExpenses
		{
			get
			{
				return this._DetailExpenses;
			}
			set
			{
				if ((this._DetailExpenses != value))
				{
					this._DetailExpenses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Participant", DbType="NVarChar(350)")]
		public string Participant
		{
			get
			{
				return this._Participant;
			}
			set
			{
				if ((this._Participant != value))
				{
					this._Participant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GL", DbType="VarChar(50)")]
		public string GL
		{
			get
			{
				return this._GL;
			}
			set
			{
				if ((this._GL != value))
				{
					this._GL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IO", DbType="VarChar(50)")]
		public string IO
		{
			get
			{
				return this._IO;
			}
			set
			{
				if ((this._IO != value))
				{
					this._IO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyCode", DbType="VarChar(50)")]
		public string CompanyCode
		{
			get
			{
				return this._CompanyCode;
			}
			set
			{
				if ((this._CompanyCode != value))
				{
					this._CompanyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileAttach", DbType="NVarChar(350)")]
		public string FileAttach
		{
			get
			{
				return this._FileAttach;
			}
			set
			{
				if ((this._FileAttach != value))
				{
					this._FileAttach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costcenter", DbType="VarChar(50)")]
		public string Costcenter
		{
			get
			{
				return this._Costcenter;
			}
			set
			{
				if ((this._Costcenter != value))
				{
					this._Costcenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyDescription", DbType="NVarChar(150)")]
		public string CurrencyDescription
		{
			get
			{
				return this._CurrencyDescription;
			}
			set
			{
				if ((this._CurrencyDescription != value))
				{
					this._CurrencyDescription = value;
				}
			}
		}
	}
	
	public partial class sp_getTravelDetailSalesResult
	{
		
		private string _Code_FK;
		
		private System.DateTime _FDate;
		
		private System.DateTime _TDate;
		
		private string _PurposeMorning;
		
		private string _PurposeAfter;
		
		private System.Nullable<decimal> _ID;
		
		private string _Note;
		
		public sp_getTravelDetailSalesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_FK", DbType="VarChar(50)")]
		public string Code_FK
		{
			get
			{
				return this._Code_FK;
			}
			set
			{
				if ((this._Code_FK != value))
				{
					this._Code_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime NOT NULL")]
		public System.DateTime FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDate", DbType="DateTime NOT NULL")]
		public System.DateTime TDate
		{
			get
			{
				return this._TDate;
			}
			set
			{
				if ((this._TDate != value))
				{
					this._TDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurposeMorning", DbType="NVarChar(500)")]
		public string PurposeMorning
		{
			get
			{
				return this._PurposeMorning;
			}
			set
			{
				if ((this._PurposeMorning != value))
				{
					this._PurposeMorning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurposeAfter", DbType="NVarChar(500)")]
		public string PurposeAfter
		{
			get
			{
				return this._PurposeAfter;
			}
			set
			{
				if ((this._PurposeAfter != value))
				{
					this._PurposeAfter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
